# Собрать многофайловый проект
# Подсказка: Опция -I в gcc помогает решить проблему с поиском заголовочных файлов. (#include "" No such file or directory)
# Для использования make его необходимо установить: sudo apt install make

main:
	gcc -I ./pipes ./app/main.c -I ./background background/background.c pipes/read_pipe.c pipes/write_pipe.c -o laba12


